name: main_workflow
on:
  push:
    branches:
      - nodejs_jest_job
      - nodejs_linter_job
      - nodejs_nodeversions_job
      - nodejs_environment_job
      - nodejs_test_error

jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Node versions
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Linter execution
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true

  text-execution: 
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm run test
        if: failure()
        run: echo "Tests failed"

  environment_test_execution:
    runs-on: ubuntu-latest
    needs: [linter-execution, text-execution]
    steps: 
      - name: Hello world environment
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: "2DAW Joan González"