name: telegram_bot_workflow
on: 
  push:
    branches:
      - send_telegram_action

jobs:
  send_telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Send Telegram
        run: npm start
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
